model:
  params:
    autoencoder_config:
      model_size: big
      params:
        encoder_config:
          params:
            in_ch_proj_dim: 128
            conv1d_channels: [128, 128, 256, 256, 512, 512]
            z_channels: 4